name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Ajusta a la versión de Node.js que utiliza tu proyecto

    - name: Install dependencies
      run: |
            cd app
            npm install

    - name: Run tests
      run: npm test

    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/proyecto/MIPSTranslator/
          git pull origin main
          git status
          docker stop mipstranslator-app
          docker rm mipstranslator-app
          docker build -t mipstranslatori .
          docker run -d -it -p 5008:4200 --restart unless-stopped --name mipstranslator-app mipstranslatori
